rmate: update version

diff --git a/bin/rmate b/bin/rmate
--- a/bin/rmate
+++ b/bin/rmate
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # rmate
-# Copyright (C) 2011-2016 by Harald Lapp <harald@octris.org>
+# Copyright (C) 2011-2018 by Harald Lapp <harald@octris.org>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -33,8 +33,8 @@
 
 # init
 #
-version="0.9.8"
-version_date="2016-04-14"
+version="1.0.1"
+version_date="2018-01-08"
 version_string="rmate-sh $version ($version_date)"
 
 # determine hostname
@@ -67,7 +67,7 @@ function load_config {
     local port_pattern="^port(:[[:space:]]+|=)([0-9]+)"
 
     if [ -f "$rc_file" ]; then
-        while read row; do
+        while read -r row; do
             if [[ "$row" =~ $host_pattern ]]; then
                 host=${BASH_REMATCH[2]}
             elif [[ "$row" =~ $port_pattern ]]; then
@@ -86,10 +86,10 @@ port="${RMATE_PORT:-$port}"
 
 
 # misc initialization
-filepath=""
-selection=""
-displayname=""
-filetype=""
+filepaths=()
+displaynames=()
+selections=()
+filetypes=()
 verbose=false
 nowait=true
 force=false
@@ -97,7 +97,7 @@ force=false
 # process command-line parameters
 #
 function showusage {
-    echo "usage: $(basename $0) [arguments] file-path  edit specified file
+    echo "usage: $(basename $0) [arguments] [--] file-path  edit specified file
    or: $(basename $0) [arguments] -          read text from stdin
 
 -H, --host HOST  Connect to HOST. Use 'auto' to detect the host from
@@ -123,29 +123,42 @@ function log {
 }
 
 function dirpath {
-    (cd `dirname $1` >/dev/null 2>/dev/null; pwd -P)
+    (cd "$(dirname "$1")" >/dev/null 2>/dev/null || { echo "unable to cd to $1 directory" 1>&2; exit; } ; pwd -P)
 }
 
 function canonicalize {
-    filepath="$1"
-    dir=`dirpath "$filepath"`
+    local filepath="$1"
+    local relativepath
+    local result
+
+    if [[ "${filepath:0:1}" = "-" ]]; then
+        filepath="./$filepath"
+    fi
+
+    local dir=$(dirpath "$filepath")
+    
     if [ -L "$filepath" ]; then
-        relativepath=`cd "$dir"; readlink \`basename "$filepath"\``
-        result=`dirpath "$relativepath"`/`basename "$relativepath"`
+        relativepath=$(cd "$dir" || { echo "unable to cd to $dir" 1>&2; exit; } ; readlink "$(basename "$filepath")")
+        result=$(dirpath "$relativepath")/$(basename "$relativepath")
     else
-        result=`basename "$filepath"`
+        result=$(basename "$filepath")
         if [ "$dir" = '/' ]; then
             result="$dir$result"
         else
             result="$dir/$result"
         fi
     fi
-    echo $result
+    
+    echo "$result"
 }
 
 while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
     case $1 in
         -)
+            break
+            ;;
+        --)
+            shift
             break
             ;;
         -H|--host)
@@ -163,15 +176,15 @@ while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
             nowait=true
             ;;
         -l|--line)
-            selection=$2
+            selections+=($2)
             shift
             ;;
         -m|--name)
-            displayname=$2
+            displaynames+=($2)
             shift
             ;;
         -t|--type)
-            filetype=$2
+            filetypes+=($2)
             shift
             ;;
         -n|--new)
@@ -184,7 +197,7 @@ while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
             verbose=true
             ;;
         --version)
-            echo $version_string
+            echo "$version_string"
             exit 1
             ;;
         -h|-\?|--help)
@@ -192,7 +205,7 @@ while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
             exit 1
             ;;
         +[0-9]*)
-            selection=${1:1}
+            selections+=(${1:1})
             ;;
         *)
             showusage
@@ -207,11 +220,11 @@ if [[ "$host" = "auto" && "$SSH_CONNECTION" != "" ]]; then
     host=${SSH_CONNECTION%% *}
 fi
 
-filepath="$1"
+filepaths=("$@")
 
-if [ "$filepath" = "" ]; then
+if [ "${filepaths[*]}" = "" ]; then
     if [[ $nowait = false ]]; then
-        filepath='-'
+        filepaths=('-')
     else
         case "$-" in
             *i*)
@@ -219,53 +232,103 @@ if [ "$filepath" = "" ]; then
                 exit 1
                 ;;
             *)
-                filepath='-'
+                filepaths=('-')
                 ;;
         esac
     fi
 fi
 
-shift
-if [ ! "${#@}" -eq 0 ]; then
-    echo "There is more than one file specified. Opening only $filepath and ignoring other."
-fi
-
-if [ "$filepath" != "-" ]; then
-    realpath=`canonicalize "$filepath"`
-    log $realpath
-
-    if [ -d "$filepath" ]; then
-        echo "$filepath is a directory and rmate is unable to handle directories."
-        exit 1
-    fi
-
-    if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
-        if [[ $force = false ]]; then
-            echo "File $filepath is not writable! Use -f to open anyway."
-            exit 1
-        elif [[ $verbose = true ]]; then
-            log "File $filepath is not writable! Opening anyway."
-        fi
-    fi
-
-    if [ "$displayname" = "" ]; then
-        displayname="$hostname:$filepath"
-    fi
-else
-    displayname="$hostname:untitled"
-fi
 
 #------------------------------------------------------------
 # main
 #------------------------------------------------------------
+
+function open_file {
+    local index="$1"
+    local filepath="${filepaths[$index]}"
+    local selection="${selections[$index]}"
+    local filetype="${filetypes[$index]}"
+    local displayname="${displaynames[$index]}"
+    local realpath
+    local data
+
+    if [ "$filepath" != "-" ]; then
+        realpath=$(canonicalize "$filepath")
+        log "$realpath"
+
+        if [ -d "$filepath" ]; then
+            echo "$filepath is a directory and rmate is unable to handle directories."
+            exit 1
+        fi
+
+        if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
+            if [[ $force = false ]]; then
+                echo "File $filepath is not writable! Use -f to open anyway."
+                exit 1
+            elif [[ $verbose = true ]]; then
+                log "File $filepath is not writable! Opening anyway."
+            fi
+        fi
+
+        if [ "$displayname" = "" ]; then
+            displayname="$hostname:$filepath"
+        fi
+    else
+        displayname="$hostname:untitled"
+    fi
+
+    echo "open" 1>&3
+    echo "display-name: $displayname" 1>&3
+    echo "real-path: $realpath" 1>&3
+    echo "data-on-save: yes" 1>&3
+    echo "re-activate: yes" 1>&3
+    echo "token: $filepath" 1>&3
+
+    if [[ $new = true ]]; then
+        echo "new: yes"  1>&3
+    fi
+
+    if [ "$selection" != "" ]; then
+        echo "selection: $selection" 1>&3
+    fi
+
+    if [ "$filetype" != "" ]; then
+        echo "file-type: $filetype" 1>&3
+    fi
+
+    if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
+        filesize=$(($(wc -c <"$realpath")))
+        echo "data: $filesize" 1>&3
+        cat "$realpath" 1>&3
+    elif [ "$filepath" = "-" ]; then
+        if [ -t 0 ]; then
+            echo "Reading from stdin, press ^D to stop"
+        else
+            log "Reading from stdin"
+        fi
+
+        # preserve trailing newlines
+        data=$(cat; echo x)
+        data=${data%x}
+        filesize=$(($(echo -ne "$data" | wc -c)))
+        echo "data: $filesize" 1>&3
+        echo -n "$data" 1>&3
+    else
+        echo "data: 0" 1>&3
+    fi
+
+    echo 1>&3
+}
+
 function handle_connection {
     local cmd
     local name
     local value
     local token
     local tmp
+    local content
 
-    while read 0<&3; do
+    while read -r 0<&3; do
         REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
         REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
 
@@ -274,7 +337,7 @@ function handle_connection {
         token=""
         tmp=""
 
-        while read 0<&3; do
+        while read -r 0<&3; do
             REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
             REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
 
@@ -306,14 +369,14 @@ function handle_connection {
         if [[ "$cmd" = "close" ]]; then
             log "Closing $token"
             if [[ "$token" == "-" ]]; then
-                echo -n "$CONTENT"
+                echo -n "$content"
             fi
         elif [[ "$cmd" = "save" ]]; then
             log "Saving $token"
             if [ "$token" != "-" ]; then
                 cat "$tmp" > "$token"
             else
-                CONTENT=`cat "$tmp"`
+                content=$(cat "$tmp")
             fi
             rm "$tmp"
         fi
@@ -324,58 +387,21 @@ function handle_connection {
 
 # connect to textmate and send command
 #
-exec 3<> /dev/tcp/$host/$port
+exec 3<> "/dev/tcp/$host/$port"
 
 if [ $? -gt 0 ]; then
     echo "Unable to connect to TextMate on $host:$port"
     exit 1
 fi
 
-read server_info 0<&3
+read -r server_info 0<&3
 
 log $server_info
 
-echo "open" 1>&3
-echo "display-name: $displayname" 1>&3
-echo "real-path: $realpath" 1>&3
-echo "data-on-save: yes" 1>&3
-echo "re-activate: yes" 1>&3
-echo "token: $filepath" 1>&3
+for i in "${!filepaths[@]}"; do
+    open_file "$i"
+done
 
-if [[ $new = true ]]; then
-    echo "new: yes"  1>&3
-fi
-
-if [ "$selection" != "" ]; then
-    echo "selection: $selection" 1>&3
-fi
-
-if [ "$filetype" != "" ]; then
-    echo "file-type: $filetype" 1>&3
-fi
-
-if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
-    filesize=`ls -lLn "$realpath" | awk '{print $5}'`
-    echo "data: $filesize" 1>&3
-    cat "$realpath" 1>&3
-elif [ "$filepath" = "-" ]; then
-    if [ -t 0 ]; then
-        echo "Reading from stdin, press ^D to stop"
-    else
-        log "Reading from stdin"
-    fi
-
-    # preserve trailing newlines
-    data=`cat; echo x`
-    data=${data%x}
-    filesize=$(echo -ne "$data" | wc -c)
-    echo "data: $filesize" 1>&3
-    echo -n "$data" 1>&3
-else
-    echo "data: 0" 1>&3
-fi
-
-echo 1>&3
 echo "." 1>&3
 
 if [[ $nowait = true ]]; then
